repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
      - id: pyupgrade

  - repo: local
    hooks:
      - id: mypy
        name: run mypy
        language: system
        entry: bash -c 'poetry run mypy "${@/backend\//./}"' --
        types: [python]
        files: ^backend/

      - id: flake8
        name: run flake8
        language: system
        entry: bash -c 'poetry run flake8 "${@/backend\//./}"' --
        types: [python]

      - id: isort
        name: run isort
        language: system
        entry: bash -c 'poetry run isort "${@/backend\//./}"' --
        types: [python]

      - id: black
        name: run black
        language: system
        entry: bash -c 'poetry run black "${@/backend\//./}"' --
        types: [python]
